data: 
  test_size: 0.1 
  val_size: 0.2      # val_size * (1 - test_size) * N
  random_state: 42


s_learner: 
  iterations: 313
  learning_rate: 0.01
  depth: 6
  l2_leaf_reg: 3
  random_strength: 1
  bagging_temperature: 0.2

t_learner: 
  treatment_learner: 
    iterations: 343
    learning_rate: 0.01
    depth: 5
    l2_leaf_reg: 3
    random_strength: 1
    bagging_temperature: 0.2
  control_learner: 
    iterations: 322
    learning_rate: 0.01
    depth: 6
    l2_leaf_reg: 3
    random_strength: 1
    bagging_temperature: 0.2

tarnet: 
  hidden_dim: 54
  features_dim: 54
  learning_rate: 0.001
  epochs: 10
  batch_size: 128
  weight_decay: 0.0001
  momentum: 0.9
  scheduler: 
    name: StepLR
    step_size: 10
    gamma: 0.1

evaluate:
  at_k: 0.3
  